# Generated by Django 4.0.4 on 2022-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка №4'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка №1'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка №3'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка №2'),
        ),
    ]
