# Generated by Django 4.0.4 on 2022-04-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_news_image_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='photos/<built-in function id><django.db.models.fields.CharField>/fourth.png', verbose_name='Картинка №4'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='photos/<built-in function id><django.db.models.fields.CharField>/main.png', verbose_name='Представляемая картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='photos/<built-in function id><django.db.models.fields.CharField>/third.png', verbose_name='Картинка №3'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='photos/<built-in function id><django.db.models.fields.CharField>/second.png', verbose_name='Картинка №2'),
        ),
    ]
